#!/bin/sh
# repo: git@github.com:shanemcdo/photo_resizer.git
# dir: $CODING_DIR/python/photo_resizer
# branch: main

dir="$CODING_DIR/python/photo_resizer/"
source "$dir/venv/bin/activate"
"$dir/main.py" "$@"
