#!/bin/sh

while IFS=',' read -r session dir cmd; do
	if tmux has-session -t "$session" 2>/dev/null; then
		continue
	fi
	echo "Creating $session"
	if [ ! -d "$dir" ]; then
		echo "'$dir' is not a valid directory"
		continue
	fi
	tmux new-session -d -s "$session" -c "$dir" 
	tmux split-window -h -c "$dir"
	tmux send-keys "$cmd" C-m
done << EOF 
Transactions,/Users/shane/coding/python/transaction_tracker/,./watcher
Weight,/Users/shane/coding/python/weightloss_progress/,./watcher
EOF
