# source the cargo environment for rust
. "$HOME/.cargo/env"

# add util-linux bins to path
# to reinstall do brew install util-linux
export PATH="/opt/homebrew/opt/util-linux/bin:$PATH"
export PATH="/opt/homebrew/opt/util-linux/sbin:$PATH"

# add openjdk to path
# to reinstall do brew install openjdk
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

# add python modules to path
export PATH="/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/bin:$PATH"

# Directories
export NOTE_FOLDER="$HOME/dropbox/note_folder"
export DOTFILES_DIR="$HOME/dotfiles"
export SCHOOL_DIR="$HOME/dropbox/school/fall2023"
export CODING_DIR="$HOME/coding"
export TEMP_DIR="$HOME/temp"
export SCRIPT_DIR="$DOTFILES_DIR/scripts"

# editing fpath
export fpath=(
/opt/homebrew/share/zsh/site-functions
"${fpath[@]}"
)

# add scripts to path
export PATH="$PATH:$SCRIPT_DIR"

# show dotfiles in fzf
export FZF_DEFAULT_COMMAND="find . -type f"

# the editor of choice
export EDITOR="nvim"
export VISUAL="$EDITOR"

# search engine stuff
export SEARCH_ENGINE="https://duckduckgo.com/"
export SEARCH_ENGINE_QUERY="$SEARCH_ENGINE?q="

# chrome stash for:
#   - $SCRIPT_DIR/pop_chrome_tab
#   - $SCRIPT_DIR/push_chrome_tab
export CHROME_STASH="$HOME/dropbox/chrome_stash.txt"

# list of todo items, done and not done for:
#   - git@github.com:shanemcdo/todo_rs
export TODO_LIST="$HOME/dropbox/todos/list.txt"
export TODO_DONE_LIST="$HOME/dropbox/todos/done_list.txt"

# clipboard file for mclip script:
#   - $SCRIPT_DIR/mclip
export MCLIP_FILE="$HOME/dropbox/mclip_file.txt"

# Workout tracker data
#   - git@github.com:shanemcdo/WorkoutTracker.git
export WORKOUT_DATA_PATH="$HOME/dropbox/workout_data.json"

# Weight tracker data
#   - git@github.com:shanemcdo/weight_tracker.git
export WEIGHT_TRACKER_PATH="$HOME/dropbox/weight_data.pickle"

# chain saw man tracker
# - $SCRIPT_DOR/csm
export CSM_CH_PATH="$HOME/dropbox/csm_ch.txt"

# cdfl - change directory from list
# - $SCRIPT_DIR/cdfl
export CDFL_LIST_PATH="$HOME/dropbox/cdfl.txt"
