# allow for colors
autoload -U colors && colors

# enable ctrl-r to back search
bindkey '^R' history-incremental-search-backward
bindkey -e # enable emacs keybinds such as
# ctrl-a go to start
# ctrl-k delete everything after
# ctrl-u cut line
# ctrl-y paste line

# import other zsh files
. "$DOTFILES_DIR/zsh/alias.zsh"
. "$DOTFILES_DIR/zsh/funcs.zsh"
. "$DOTFILES_DIR/zsh/load_znap.zsh"

# load zoxide
eval "$(zoxide init zsh)"

# set custom prompt
set_prompt
